name: py-rocket-oceanhackweek 
# 2025-11-19
channels:
  - conda-forge
  - nodefaults

dependencies:
  # Core scientific python stack
  - cython # optimization, C API access
  - flox # optimization, xarray operations
  - hypothesis # needed by numpy testing tools
  - networkx
  - numba # high-performance numerics
  - numbagg
  - numpy
  - opt_einsum
  - pandas
  - scikit-image
  - scikit-learn
  - scipy
  - statsmodels
  - pymannkendall # non-parametric Mann-Kendall trend analysis
  - xarray>=2024.05.0
  - cf_xarray

  # Visualization packages
  - bokeh
  - cartopy # geospatial plotting with matplotlib
  - geemap
  - geoviews
  - hvplot
  - ipyleaflet
  - ipympl # This enables matplotlib interaction with jupyter widgets
  - leafmap
  - lonboard
  - matplotlib
  - basemap
  - basemap-data
  - plotly
  - seaborn # statistical plotting with matplotlib
  - cmocean # colormaps for ocean
  - palettable
  - imageio # helps writing image files
  - apng # create animation from multiple png
  - holoviews
  - graphviz
  - regionmask # create masks of (geo)spatial regions
  - contextily # base maps

  # Machine Learning packages
  - py-xgboost~=2.1.1=cpu*

  # Geospatial data packages
  - geopandas>=0.14.4
  - rasterio
  - rioxarray
  - rasterstats # summarize geospatial raster datasets based on vector geometries
  - pyresample # resampling geospatial image data
  - shapely # manipulation and analysis of planar geometric objects
  - pyproj
  - datashader

  # File formats and file management, download, dataset caching
  - h5py
  - h5netcdf
  - nco
  - pynco # python style access to the NetCDF Operators (NCO)
  - pooch
  - zarr
  - kerchunk
  - rechunker
  - cftime # for decoding time units and variable values in a netCDF file
  - h5coro # reading HDF5 data stored in S3
  - hdf5plugin # provides HDF5 compression filters
  - lxml # processing XML and HTML
  - osmnx # Access and manipulate OSM data

  # Cloud access tools and libraries
  - awscli
  - awscliv2
  - boto3
  - s3fs>=2023.6.0
  # handle login and similar details for accessing earthdata protected data
  # Access datasets exposed via STAC
  - pystac-client
  - stackstac
  # Access datasets exposed via intake catalogs
  - intake
  - intake-esm>=2023.7.7
  # 2025-11-19: intake-stac hasn't been meaninfully updated since 2022-05
  # - intake-stac==0.4.0
  # 2025-11-19: intake-xarray 0.6.1 is from 2022-08, and there are newer releases
  - intake-xarray>=0.6.1
  - gcsfs>=2023.5.0
  - certifi # Root Certificates for validating the trustworthiness of SSL certificates.

  # Specific cloud access libraries
  - copernicusmarine # get data from copernicus
  - earthaccess>=0.11.0 # get data from nasa earth access
  - erddapy # connect to erddap servers
  - ecmwflibs # wraps some of European Centre for Medium-Range Weather Forecasts libraries
  - harmony-py

  # Distributed computing
  - dask>=2023.12.1
  - dask-labextension
  - dask-geopandas

  # Other useful generic python packages
  - pip
  - pillow # Python imaging library, useful for many image-related tasks
  - pytest
  - pytest-cov
  - pep8
  - flake8
  - tqdm # progress bars, with notebook support
  - joblib # lightweight pipelining in Python
  - papermill
  - tldr
  - zip # installs zip terminal command; not a Python package per se?

  # Jupyter Lab language packs for Spanish and Portuguese
  - jupyterlab-language-pack-es-es
  - jupyterlab-language-pack-pt-br

  # Packages specific to climate and ocean data work
  - argopy
  - echopype
  - eofs
  - esmpy
  - gsw
  - oceans
  - parcels
  - pyco2sys
  - python-cdo
  - seawater
  - xmip

  # Desktop tools
  - qgis 
  - pyopencl  # Maybe needed for qgis? https://github.com/conda-forge/qgis-feedstock/issues/263
  # Resolves warning "No ICDs were found": https://github.com/CryoInTheCloud/hub-image/issues/50
  - ocl-icd-system
  
  # Quarto is installed via R installation in py-rocket-base
  # - quarto==1.5.57
  - pip:
    - xq # Apply XPath expressions to XML
    - jupyterlab-quarto
    - google-cloud-storage
    # Last release on 2022-10, but the github repo is being actively updated
    # - git+https://github.com/AntSimi/py-eddy-tracker.git
