name: acoustics
channels:
  - conda-forge
  - nodefaults

dependencies:
  - pyworms
  - pip
  - pip:
    - orjson
    - echosms
    - fastapi[standard]
    - stream_zip
    - rtoml
    - jsonschema_rs
